import type { Metadata } from 'next';
import { Anuphan } from 'next/font/google';
import './globals.css';
import LineProvider from '../contexts/liff';

const anuphan = Anuphan({
  variable: '--font-anuphan',
  subsets: ['latin', 'thai'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anuphan.variable} vsc-initialized antialiased`}>
        <LineProvider>{children}</LineProvider>
      </body>
    </html>
  );
}
